# Generated by Django 5.2.1 on 2025-05-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={},
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='notes',
        ),
        migrations.AddField(
            model_name='lead',
            name='confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_person',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estimated_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('inprogress', 'In Progress'), ('lost', 'Lost'), ('won', 'Won')], default='new', max_length=25),
        ),
    ]
